### ISSUE TITLE
rename: Invalid cross-device link

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/zsync2#13]
Upstream issue, continuing https://github.com/AppImage/AppImageUpdate/issues/50.

The initial temporary files created by the legacy libzsync are created in the current working directory and not in the target directory (unlike the `.part` file which is managed by the C++ code in libzsync2). When trying to move, or actually, `rename()` this file, this might yield an `invalid cross-device link` error, unless one would copy the file and remove the old one like the `mv` command does in such cases.

Instead of doing this, the file should just be created in the right location, i.e., the target directory. That'll also allow for finding the temp files more easily after updates failed.

Relevant code:

https://github.com/TheAssassin/zsync2/blob/d7942eac257258d326c19fdc031f301a766abdda/lib/librcksum/state.c#L56-L57

This path needs to incorporate the target file path, determine the directory path, and prepend that. The path will have to be passed to the `struct rcksum_state` in the initializer, I guess.

**Comment by TheAssassin** [comment]
Turned out to be slightly more complex than expected. After two failed attempts, I was able to implement the desired behavior with just a few changes in libzsync2, and some major ones in libzsync.

I've tested everything with the scenarios described in https://github.com/AppImage/AppImageUpdate/issues/50. Looking good so far as of https://github.com/TheAssassin/zsync2/commit/2fea71d0f23017b220744f8ebd248f9723ed6fe3. Closing this now.

**Comment by probonopd** [comment]
Just to make sure - we are not copying files between different partitions, are we?
I think the "new" file should be constructed right from the beginning in the target location rather than `$CWD` or something. Think biiiiig files.

**Comment by TheAssassin** [comment]
Of course not. I've had to change a few constructors etc. to be able to pass a directory that should be used to create the `rcksum-*` files instead of the current working directory. Now, they're created in the same location like all the other files. This is achieved by re-using the `cwd` variable I've introduced to fix https://github.com/AppImage/AppImageUpdate/issues/37.

**Comment by benoit-pierre** [comment]
This does not seem to take into account the `-o` option, e.g. using `zsync2 -o another_filesystem/appimage ...`.

**Comment by benoit-pierre** [comment]
Yeah, temporary files are created in `$CWD`, instead of the output directory.

**Comment by benoit-pierre** [comment]
Tentative patch:
```diff
 src/zsclient.cpp | 15 ++++++++++++++-
 1 file changed, 14 insertions(+), 1 deletion(-)

diff --git i/src/zsclient.cpp w/src/zsclient.cpp
index 6c75a37..c465ab0 100644
--- i/src/zsclient.cpp
+++ w/src/zsclient.cpp
@@ -336,7 +336,20 @@ namespace zsync2 {
                 f = fmemopen(buffer.data(), buffer.size(), "r");
             }
 
-            if ((zs = zsync_begin(f, (headersOnly ? 1 : 0), (cwd.empty() ? nullptr : cwd.c_str()))) == nullptr) {
+            char *target_dir = nullptr;
+
+            if (!this->pathToLocalFile.empty()) {
+                std::size_t last_slash = this->pathToLocalFile.find_last_of('/');
+                if (last_slash != std::string::npos && last_slash > 0)
+                    target_dir = strndup(this->pathToLocalFile.c_str(), last_slash);
+            }
+
+            if (target_dir == nullptr && !cwd.empty())
+                target_dir = strdup(cwd.c_str());
+
+            zs = zsync_begin(f, (headersOnly ? 1 : 0), target_dir);
+            free(target_dir);
+            if (zs == nullptr) {
                 issueStatusMessage("Failed to parse .zsync file!");
                 return nullptr;
             }
```
