### ISSUE TITLE
Ability to check whether file requires update

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/zsync2#3]

**Comment by TheAssassin** [comment]
`-j` option is implemented, also there's a method `checkForChanges` available.

**Comment by probonopd** [comment]
Please don't forget to update the README.md (or other documentation) along the way whenever such new cool functionality becomes available.

**Comment by TheAssassin** [comment]
CLI compatibility is one of the points of the sprint. I'll post an extract from the help menu then.

API docs will follow as soon as the API is in a consistent state. I think I can generate them from source with little effort.

**Comment by probonopd** [comment]
OK, cool!
