### ISSUE TITLE
Implement -v --verbose

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/zsync2#6]
Currently we can set an environment variable `CURLOPT_VERBOSE=1` but one has to remember this. It would be more convenient if we could achieve the same by passing in `-v` or `--verbose` as a parameter.

**Comment by TheAssassin** [comment]
zsync2 is pretty verbose already. `CURLOPT_VERBOSE` only triggers curl to post every HTTP request.

Should `-v` therefore primarly `putenv("CURLOPT_VERBOSE=1")`?

**Comment by probonopd** [comment]
Yes

**Comment by TheAssassin** [comment]
Implemented in https://github.com/TheAssassin/zsync2/commit/9614de8a3d1f37758f16a0e259556bf32622016e.
