### ISSUE TITLE
.zs-old file left over

### ISSUE THREAD

**Issue by probonopd** [TheAssassin/zsync2#7]
.zs-old file is left over when trying to download an already-downloaded file:

```
wget https://github.com/TheAssassin/zsync2/releases/download/continuous/zsync2-continuous-x86_64.AppImage
chmod +x zsync2-continuous-x86_64.AppImage 
./zsync2-continuous-x86_64.AppImage https://github.com/TheAssassin/zsync2/releases/download/continuous/zsync2-continuous-x86_64.AppImage.zsync
ls
# zsync2-continuous-x86_64.AppImage # good!
# zsync2-continuous-x86_64.AppImage.zs-old # bad!
```

**Comment by TheAssassin** [comment]
That code was ported from zsync_curl actually. Could you check how zsync_curl behaves?

**Comment by probonopd** [comment]
Badly, so much I still remember from the back of my memory...

**Comment by TheAssassin** [comment]
We could make the zsync2 CLI app behave like AppImageUpdate and perform a check for server-side changes before starting the update process, at the moment it just runs the update and performs the unnecessary I/O I want to avoid.

**Comment by probonopd** [comment]
Yes, why not.
