### ISSUE TITLE
Fix openGzFile

### ISSUE THREAD

**Issue by TheAssassin** [TheAssassin/zsync2#9]
The implementation of `openGzFile()` is broken at the moment. Thanks to @pamarcos for bringing this up.

First of all, the use of `fopencookie` doesn't make sense, `f` isn't taken into account in the `open/read/write/close` functions, and if it went out of scope, there is no chance to access the file any more.

We'll have to use a few C++11 lambdas when creating the `cookie_io_functions_t` object, which basically call `gz*` appropriately, and store (copy) pointers to `f` in them. Then, we can clean it up properly.

Also, ideally, the function is designed so that we can easily drop in platform specific implementations for other OSes, like macOS or Windows.

**Comment by probonopd** [comment]
If `zsync2` wants to become a drop-in replacement for for `zsync`, then yes, macOS and Windows are needed, too.

**Comment by TheAssassin** [comment]
There is no easy way to do it on Windows at the moment. Those parts of libzsync should just be replaced with standard library or other platform independent code. And that's when I'll begin to work on cross platform. For now, focusing on BSD/macOS/Linux.

**Comment by probonopd** [comment]
Perhaps a Windows user will contribute that code, in which case I am sure a PR would be welcome :100:

**Comment by TheAssassin** [comment]
Sure, of course. Right now, it's not a priority.

**Comment by TheAssassin** [comment]
I think that should do, but I couldn't test it in depth. It *appears* to be right this way. Now, we just need to implement the same thing with `funopen()`, and we'll have support for BSD and macOS.
